### ISSUE TITLE
TODO: refactoring list

### ISSUE THREAD

**Issue by Jeong-jj** [Buggureomi/buggureomi-fe#15]
## Refactoring Target

- [x] type 정리
- [x] 버튼 아이콘 적용
- [x] 사용자 답변 색상 UI 적용할 부분 정의
- [ ] rotuer 정리
  - [ ] route 별 layout 재구성
- [x] store 추가
- [x] api token interceptor
